"""Generate the gitignored Kind values file for external host dependencies."""

from __future__ import annotations

import argparse
import ipaddress
import os
import tempfile
from pathlib import Path

import yaml


HERE = Path(__file__).resolve().parent
DEFAULT_OUTPUT = HERE / "values.generated.yaml"


def values(host_cidr: str, *, keycloak_port: int, postgres_port: int, kms_port: int) -> dict:
    network = ipaddress.ip_network(host_cidr, strict=True)
    if network.num_addresses != 1:
        raise ValueError("host CIDR must identify exactly one Docker host address (/32 or /128)")
    host = "host.docker.internal"
    public_issuer = f"http://localhost:{keycloak_port}/realms/xa-guard"
    backchannel = f"http://{host}:{keycloak_port}"
    return {
        "referenceInfra": {"enabled": True, "testFaults": True},
        "global": {
            "oidc": {
                "issuer": public_issuer,
                "discoveryUrl": f"{public_issuer}/.well-known/openid-configuration",
                "jwksUri": f"{public_issuer}/protocol/openid-connect/certs",
                "backchannelBaseUrl": backchannel,
                "tokenEndpoint": f"{backchannel}/realms/xa-guard/protocol/openid-connect/token",
                "referenceHttpHosts": "host.docker.internal,localhost,127.0.0.1",
            },
            "postgres": {"sslMode": "disable"},
            "kms": {
                "provider": "http",
                "endpoint": f"http://{host}:{kms_port}",
                "referenceHttpHosts": "host.docker.internal",
            },
        },
        "ingress": {"enabled": False},
        "networkPolicy": {
            "dependencies": {
                "oidc": {"cidrs": [host_cidr], "ports": [keycloak_port]},
                "postgres": {"cidrs": [host_cidr], "ports": [postgres_port]},
                "keyProvider": {"cidrs": [host_cidr], "ports": [kms_port]},
            }
        },
    }


def write_values(output: Path, data: dict) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    rendered = (
        "# Generated by deploy/kind/generate_values.py. Contains endpoint topology, not secrets.\n"
        + yaml.safe_dump(data, sort_keys=False)
    )
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=output.parent, delete=False) as handle:
        handle.write(rendered)
        pending = Path(handle.name)
    os.replace(pending, output)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host-cidr", required=True, help="Docker host address as /32 or /128")
    parser.add_argument("--keycloak-port", type=int, default=13081)
    parser.add_argument("--postgres-port", type=int, default=15432)
    parser.add_argument("--kms-port", type=int, default=13083)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    write_values(
        args.output,
        values(
            args.host_cidr,
            keycloak_port=args.keycloak_port,
            postgres_port=args.postgres_port,
            kms_port=args.kms_port,
        ),
    )
    print(args.output.resolve())


if __name__ == "__main__":
    main()
